const tableData = [{
    "id": 1,
    "first_name": "Daryle",
    "last_name": "Martinie",
    "email": "dmartinie0@kickstarter.com",
    "gender": "Male",
    "ip_address": "96.127.62.173"
  }, {
    "id": 2,
    "first_name": "Barnabe",
    "last_name": "Hurche",
    "email": "bhurche1@macromedia.com",
    "gender": "Male",
    "ip_address": "132.231.107.205"
  }, {
    "id": 3,
    "first_name": "Nina",
    "last_name": "Raistrick",
    "email": "nraistrick2@intel.com",
    "gender": "Female",
    "ip_address": "44.148.236.245"
  }, {
    "id": 4,
    "first_name": "Amalia",
    "last_name": "Yakolev",
    "email": "ayakolev3@nytimes.com",
    "gender": "Female",
    "ip_address": "255.204.61.217"
  }, {
    "id": 5,
    "first_name": "Bartlet",
    "last_name": "Adamthwaite",
    "email": "badamthwaite4@usda.gov",
    "gender": "Male",
    "ip_address": "187.13.11.167"
  }, {
    "id": 6,
    "first_name": "Colette",
    "last_name": "Lokier",
    "email": "clokier5@lycos.com",
    "gender": "Female",
    "ip_address": "43.118.152.202"
  }, {
    "id": 7,
    "first_name": "Hugues",
    "last_name": "Witty",
    "email": "hwitty6@clickbank.net",
    "gender": "Male",
    "ip_address": "102.76.67.83"
  }, {
    "id": 8,
    "first_name": "Luther",
    "last_name": "Statefield",
    "email": "lstatefield7@1688.com",
    "gender": "Male",
    "ip_address": "159.91.67.53"
  }, {
    "id": 9,
    "first_name": "Wallace",
    "last_name": "Hazelhurst",
    "email": "whazelhurst8@bandcamp.com",
    "gender": "Male",
    "ip_address": "30.153.155.88"
  }, {
    "id": 10,
    "first_name": "Rusty",
    "last_name": "Kloisner",
    "email": "rkloisner9@aol.com",
    "gender": "Male",
    "ip_address": "201.245.42.51"
  }]

  export default tableData;